default_stages: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: check-commit-msg
        name: Check commit message follows Conventional Commits
        entry: ./scripts/check_commit_msg.sh
        language: script
        stages: [commit-msg]

  - repo: git@github.com:psf/black.git
    rev: 23.12.1
    hooks:
    -   id: black
        args: [--line-length=79]

  - repo: git@github.com:PyCQA/flake8.git
    rev: 7.0.0
    hooks:
      - id: flake8

  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
