---
name: Deploy to production

on:
    push:
        branches:
            - main
            - ci/fix-prod-deploy  # temporarily included for testing

jobs:
    deploy_prod:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            # - name: Upload env.sh.template to server
            #   uses: appleboy/scp-action@v1.0.0
            #   with:
            #       host: ${{ secrets.SERVER_HOST }}
            #       username: ${{ secrets.SERVER_USER }}
            #       key: ${{ secrets.SERVER_SSH_KEY }}
            #       source: ./.github/workflows/config_templates/env.sh.template
            #       target: ~/

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |

                      echo "[GitHub Actions] Pulling latest changes..."
                      cd ~/armwrestling_training_planner
                      git pull origin main
                      echo "==============================="
                      echo "==============================="


                      pwd

                      echo "==============================="
                      echo "==============================="


                      echo "[GitHub Actions] Loading environment variables..."
                      if [ -f .github/workflows/config_templates/env.sh.template ]; then
                      cat .github/workflows/config_templates/env.sh.template
                      source .github/workflows/config_templates/env.sh.template
                      fi

                      echo "==============================="
                      echo "==============================="
                      echo "$VENV_PATH"
                      echo "==============================="
                      echo "==============================="

                      echo "[GitHub Actions] Creating virtual environment if missing..."
                      if [ ! -d "$VENV_PATH" ]; then
                        python3 -m venv "$VENV_PATH"
                      fi

                      echo "==============================="
                      echo "==============================="

                      echo "[GitHub Actions] Activating virtualenv..."
                      source "$VENV_PATH"/bin/activate
                      pip install -r requirements/base.txt

                      # echo "[GitHub Actions] Restarting bot service..."
                      # sudo systemctl restart armwrestling_training_bot
