---
name: Deploy to production

on:
    push:
        branches:
            - main
            - ci/fix-prod-deploy  # temporarily included for testing

jobs:
    deploy_prod:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                    REPO="git@github.com:${{ github.repository }}.git"
                    BRANCH="${{ github.ref_name }}"
                    REPO_DIR="$HOME/armwrestling_training_planner"
                    DEPLOY_DIR="$REPO_DIR/.deploy"


                    if [ ! -d "$REPO_DIR" ]; then
                      echo "[Deploy] Cloning repository to $REPO_DIR"
                      git clone "$REPO" "$REPO_DIR"
                      cd "$REPO_DIR"
                      git checkout "$BRANCH"
                    else
                      echo "[Deploy] Repository already exists. Pulling latest changes..."
                      cd "$REPO_DIR"
                      git fetch origin
                      git checkout "$BRANCH"
                      git pull origin "$BRANCH"
                    fi

                    sudo /home/armwrestling_training_bot/armwrestling_training_planner/.deploy/preparations.sh
