name: Deploy to Server

on:
  push:
    branches:
      - "feature/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "[GitHub Actions] Pulling latest changes..."
            cd ~/armwrestling_training_planner
            git pull origin main

            echo "[GitHub Actions] Activating virtualenv..."
            source venv/bin/activate
            pip install -r requirements/base.txt

            # echo "[GitHub Actions] Restarting bot service..."
            # sudo systemctl restart armwrestling_training_bot
