name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VENV_PATH: ".venv"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "[GitHub Actions] Pulling latest changes..."
            cd ~/armwrestling_training_planner
            git pull origin main

            echo "[GitHub Actions] Creating virtual environment if missing..."
            if [ ! -d "$VENV_PATH" ]; then
              python3 -m venv $VENV_PATH
            fi

            echo "[GitHub Actions] Activating virtualenv..."
            source $VENV_PATH/bin/activate
            pip install -r requirements/base.txt

            # echo "[GitHub Actions] Restarting bot service..."
            # sudo systemctl restart armwrestling_training_bot
