name: Code Quality & Tests

on:
  push:
    branches-ignore:
      - main
      - stage
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VENV_PATH: ".venv"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create virtual environment if missing
        run: |
          if [ ! -d "$VENV_PATH" ]; then
            python -m venv $VENV_PATH
          fi

      - name: Install dependencies
        run: |
          source $VENV_PATH/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

      - name: Run black (check only)
        run: black --check .

      - name: Run flake8
        run: flake8 .

      - name: Run pytest
        run: pytest